Orders queries
TheBridge-FullStackDeveloper/ecommerce-back pull request #58
Opened 2022-07-21 16:25 UTC by jaengustavof

2022-07-26 19:09 UTC, SORAYARG requested changes
![v](https://media.giphy.com/media/w89ak63KNl0nJl80ig/giphy.gif)

2022-07-26 19:09 UTC, SORAYARG commented on package.json
> +    "cors": "^2.8.5",
no necesitamos cors

2022-07-26 19:09 UTC, SORAYARG commented on queries/orders/index.js
> +       const resultOrders = orders.map((e)=>{
Lo llamaria `order` en vez de `e`

2022-07-26 19:09 UTC, SORAYARG commented on queries/orders/queries.js
> +const selectOneOrder = ({ sell_id }) => {
```
const selectOneOrder = ({ sell_id }) => {
  return sql`
  SELECT *
  FROM orders
  JOIN products
  ON orders.product_id = products.id
  JOIN sells
  ON orders.sell_id = sells.id
  WHERE sell_id = ${sell_id};
    `; 
};
```
Así tenemos mas información

2022-07-26 19:09 UTC, SORAYARG commented on queries/orders/queries.js
> +
```
const insertOneOrder = ({ quantity, sell_id, product_id }) => {
  return sql` INSERT INTO orders (quantity, sell_id, product_id) 
  VALUES (${quantity}, ${sell_id}, ${product_id});
  `;
};
```
Queries redundantes, ya tenemos los id.

2022-07-26 19:09 UTC, SORAYARG commented on queries/orders/queries.js
> +};
recordatorio: borrar todos los console.log y comentarios.

2022-07-26 19:09 UTC, SORAYARG commented on queries/product/index.js
> -const getAllProducts = (db) =>
Tienes mas archivos a parte de orders en esta PR que no deberían estar.

2022-07-28 10:38 UTC, jaengustavof commented on package.json
> +    "cors": "^2.8.5",
Sinceramente se habrá bajado durante un pull. De todos modos vamos a necesitar el cors para realizar el proceso de autorización, Lo dejamos por ahora.

2022-07-28 10:44 UTC, jaengustavof commented on queries/orders/index.js
> +       const resultOrders = orders.map((e)=>{
ok

2022-07-28 10:44 UTC, jaengustavof commented on queries/orders/queries.js
> +const selectOneOrder = ({ sell_id }) => {
Modificado

2022-07-28 10:44 UTC, jaengustavof commented on queries/orders/queries.js
> +const selectOneOrder = ({ sell_id }) => {
Ok

2022-07-28 10:44 UTC, jaengustavof commented on queries/orders/queries.js
> +
ok

2022-07-28 10:45 UTC, jaengustavof commented on queries/product/index.js
> -const getAllProducts = (db) =>
Los archivos han sido eliminados

2022-07-28 18:09 UTC, closed without merging